version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: otp-email
    hostname: rabbitmq-host
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    restart: unless-stopped

volumes:
  rabbitmq_data:
